				<!-- menu items -->
				<a href="/index.html" class="menuItem">Home</a>
				<a href="#" class="menuItem">Menu item 1</a>
				<a href="#" class="menuItem">Menu item 2</a>
				<!-- social media links -->
				<span id="menuLinks">
					<a href="#" title="Facebook"><img src="/icons/facebook.png" alt="Facebook" /></a>
					<a href="#" title="Google+"><img src="/icons/google-plus.png" alt="Google+" /></a>
					<a href="#" title="Twitter"><img src="/icons/twitter.png" alt="Twitter" /></a>
					<a href="http://www.github.com/floriandejonckheere" title="GitHub"><img src="/icons/github.png" alt="GitHub" /></a>
				</span>
