				<!-- menu items -->
				<a href="../index.html">Home</a>
				<a href="#">Menu item 1</a>
				<a href="#">Menu item 2</a>
				<!-- social media links -->
				<span id="menuLinks">
					<a href="#" title="Facebook"><i class="icon-facebook-sign"></i></a>
					<a href="#" title="Google+"><i class="icon-google-plus"></i></a>
					<a href="http://www.github.com/floriandejonckheere" title="GitHub"><i class="icon-github-alt"></i></a>
				</span>
